### PR TITLE
Update golang version to 1.18

### PR DESCRIPTION
**Pull request by soulteary**

### CODE REVIEW

**Comment by soulteary** [comment]
@looterz wow ,I didn't even have time to write an issue with a clear purpose...

**Comment by looterz** [comment]
Sorry about that, was a bit quick on the gun on mobile - been meaning to update to 1.18 for awhile now

**Comment by soulteary** [comment]
Here is an additional explanation why the version of x/sys was upgraded, Avoid confusion for latecomers.

After the upgrade of golang 1.18, it will cause the project to fail to start on macOS.

https://github.com/google/go-jsonnet/issues/596

Currently, this problem has been officially corrected earlier. like this:

https://github.com/golang/go/issues/49219


Simply put, if we encounter this kind of problem, we only need to execute

```
go get -u golang.org/x/sys
```

That's it, no side effects

**Comment by soulteary** [comment]
Sorry I didn't explain clearly.

I think I should follow the rules and submit issues first, then PRs.

I'm actually quite happy because you didn't even need me to explain why you upgraded to go 1.18 and made changes to a module, thank you for your trust. @looterz  🍻

**Pull request merged**
